# Site settings
title: Chris Zempel
email: chris.m.zempel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chris Zempel specializes in web development and user experience design
  with Ruby on Rails, Javascript, HTML5, and CSS3
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chriszempel.com" # the base hostname & protocol for your site
twitter_username: ZempTime
github_username:  ZempTime

# Build settings
markdown: kramdown
